#-------------------------------
# General Site Settings
title: CLASSICBRI
logo: # You can add own logo. For example '/images/logo.png'.
description: A place for Brian Carroll to post stuff on the internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.classicbri.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Brian Carroll
  bio: Art Director. Cartoonist. Motion Graphics Animator. I have a lot of thoughts about movies and civics.
  avatar: '/images/01.jpg'

social:
- {icon: "ion-logo-twitter", label: Twitter, link: "https://twitter.com/classicbri"}
- {icon: "ion-logo-dribbble", label: Dribbble, link: "https://dribbble.com/classicbri"}
- {icon: "ion-logo-instagram", label: Instagram (personal), link: "https://instagram.com/classicbri"}
- {icon: "ion-logo-instagram", label: Instagram (art), link: "https://instagram.com/studiolitchfield"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Brian Carroll goes by the screenname, ClassicBri.
  hero__description: Art Director in the Los Angeles area but I also have a lot of thoughts about movies, civics, and design.
  hero__image: '/images/01.jpg'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: false # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get interesting news # Add your Title
mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: carroll@lobsterback.com # Add your email for contact form
  description: # Add a description of your form

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed